### PR TITLE
Build for VS2019 & modern Python 3

### PR DESCRIPTION
**Pull request by andrey-starodubtsev**
To build NSIS using Visual Studio 2019 and Python 3.8.0 following commands were used from Developer Command Prompt for VS 2019:

```
set MSSdk=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A
scons ZLIB_W32=C:\zlib128-dll MSTOOLKIT=yes SKIPUTILS="NSIS Menu" UNICODE=yes MSVC_USE_SCRIPT=None dist-zip
```

### CODE REVIEW

**Comment by kichik** [comment]
Technically we still support Python 2.7. I think my official build system even uses that. But more importantly, Debian might?

Are all the Python changes required? Are they backward compatible?

Do you think no Linux distro still uses Python 2.7 for building NSIS?

Making Python 3 required for Windows might be easier than Linux. Honestly it's all a question of whether my build system can take it.

**Comment by andrey-starodubtsev** [comment]
As far as I understand, all suggested changes will work on Python 2.x. Just to be sure I added both Python 2.x and 3.x in build matrix in `build.yml`. Feel free to cherry pick first commit only if you think it takes to long to check Python compatibility during CI process.

**Comment by kichik** [comment]
@sredna LGTM

**Comment by sredna** [comment]
Works for me with 2.7.6 on Windows.

**Pull request closed without merging**
