### PR TITLE
Port SCons scripts to py3k

### PR DESCRIPTION
**Pull request by xantares**
This allows to build nsis when using scons together with Python3, in-progress

### CODE REVIEW

**Comment by sredna** [comment]
We are planning a release soon. Will you be able to complete the Python 3 support in a week or two?

**Comment by xantares** [comment]
for now I'm stuck at a scons error, but even if I miss the release, this does not harm python2 and can be included anyways.

**Comment by xantares** [comment]
good to go, can it be included ?

**Comment by sredna** [comment]
We appreciate the effort but I don't see the point of merging something that is not complete. We can look at it again for vNext.

**Comment by xantares** [comment]
@sredna the build completes now, it was just a list-map conversion error

**Pull request merged**
