### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by kichik** [comment]
Thanks. We don't take PRs in GitHub yet. This is just a mirror. Patches should still be submitted to [SourceForge](https://sourceforge.net/p/nsis/patches/).
@sredna might ask that you submit it again there. But he might also be able to just get the patch here.

**Comment by sredna** [comment]
I don't see any relevant changes here. e7cddf74cb4695e7171f3bd4f31faa5cb8421293 changed the branding to English for all languages.

**Comment by bovirus** [comment]
@kichik 

Sorry but I didn't understand because you didn't merge the changes.

Please read carefully the changes.

1. The language file use ANSI (not ASCII) coding system
2. One string ("Nullsoft Install System %s") is not translated (and I revided it).
3. The file is "revised by xxxxx" (not "corrected by xxx").
3. I'm the author of NSIS Italian language file and I added this info (with my email).

Then i renew the request to merge the changes.

**Comment by sredna** [comment]
1) Read that comment carefully; "dash (-) means ASCII code page". The Italian .nlf file does not use a dash so the comment does not even apply. And even if it did, the comment is correct, only ASCII will be handled correctly on systems with a different ACP.

2) It is not supposed to be translated, I already linked to the commit that changed this in my previous comment!

3) The word corrected was already there, your name was just appended to the list of people who submitted corrections.

4) Well, you are not the original author but you provided some helpful corrections and improvements. I will add your email to the credits.

And finally; you are not supposed to use GitHub pull requests, we still use SourceForge for bugs and patches and our GitHub page clearly says so on the top of the page.

**Pull request closed without merging**
